modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
[[mods]]
modId="mineagent"
version="${file.jarVersion}"
displayName="MineAgent Athletics"
authors="vister000"
displayURL="https://vis0.top"
logoFile=""
description='''Minecraft向けの汎用パルクール・アスレチックAI。Pythonとのローカルブリッジを使用して動作する非公式Minecraft Modです。'''
[[dependencies.mineagent]]
modId="neoforge"
type="required"
versionRange="[21.1.250,)"
ordering="NONE"
side="BOTH"
[[dependencies.mineagent]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
